apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: webapp
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
    - port: 30005
      protocol: TCP
      targetPort: http
      nodePort: 30006
